services:
  rabbitmq:
    image: rabbitmq:4.2.2-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
 
  producer:
    build: ./producer
    container_name: producer
    ports:
      - "3000:3000"
    volumes:
      - ./producer:/app
      - /app/node_modules
    develop:
      watch:
        - action: sync
          path: ./producer
          target: /app
          ignore:
            - node_modules/
    command: npm run dev
    depends_on:
      - rabbitmq

  consumer:
    build: ./consumer
    container_name: consumer
    volumes:
      - ./consumer:/app
      - /app/node_modules
    develop:
      watch:
        - action: sync
          path: ./consumer
          target: /app
          ignore:
            - node_modules/
    command: npm run dev
    depends_on:
      - rabbitmq
